package academy.devdojo.maratonajava.poo.exception.runtime.test;

public class RuntimeExceptionTest01 {
    public static void main(String[] args) {
        Object object = null;
        //System.out.println(object.toString());

        int nums[] = {1, 2};
        System.out.println(nums[2]);
    }
}
